layouts/partials/search/assets/css.html
layouts/partials/search/assets/js.html

Minify CSS and JS on production

---

README.md
assets/search/js/engine.ts
assets/search/js/index.ts
config.toml
layouts/partials/search/assets/js.html

Add configurable options

---

README.md
assets/search/js/index.ts
config.toml
exampleSite/layouts/_default/baseof.html

Add shortcuts options

---

assets/search/scss/_modal.scss
i18n/en.toml
i18n/zh-hans.toml
i18n/zh-hant.toml
layouts/partials/search/assets/js.html
layouts/partials/search/functions/params.html
layouts/partials/search/modal-footer.html
layouts/partials/search/modal.html

Update the footer style and information according to the configuration

---

README.md
assets/search/scss/_modal.scss
assets/search/scss/_reboot.scss
assets/search/scss/_stat.scss
exampleSite/config/_default/params.zh-hant.toml

Change style, normalize and document the CSS variables

---

README.md
exampleSite/assets/main.scss
exampleSite/layouts/_default/baseof.html
layouts/partials/search/assets/css-resource.html
layouts/partials/search/assets/css.html
layouts/partials/search/assets/js-resource.html
layouts/partials/search/assets/js.html

Add assets resources partials

---

assets/search/js/renderer.ts

Back to top when re-rendering new results

---

README.md
assets/search/js/engine.ts
assets/search/js/renderer.ts
assets/search/scss/_reboot.scss
assets/search/scss/_result.scss

Highlighting search results matches

---

README.md
assets/search/js/index.ts
assets/search/js/renderer.ts

Show the search time

---

README.md
assets/search/js/index.ts
assets/search/js/renderer.ts
assets/search/scss/_form.scss
assets/search/scss/_modal.scss
assets/search/scss/_reboot.scss
layouts/partials/search/modal.html

Improve UE

---

README.md
assets/search/js/index.ts
assets/search/js/navigator.ts
assets/search/scss/_modal.scss
assets/search/scss/_result.scss
i18n/en.toml
i18n/zh-hans.toml
i18n/zh-hant.toml
layouts/partials/search/modal-footer.html

Add results navigation support

---

assets/search/js/index.ts
assets/search/js/renderer.ts
assets/search/scss/_result.scss
exampleSite/layouts/_default/baseof.html
layouts/partials/search/assets/js-resource.html
layouts/partials/search/index.json.html

Show search results' language and taxonomies

---

assets/search/scss/_modal.scss
layouts/partials/search/modal-footer.html

Hide the footer on small screens

---

README.md
assets/search/js/engine.ts
assets/search/js/index.ts
assets/search/js/renderer.ts
assets/search/scss/_form.scss
assets/search/scss/_modal.scss
assets/search/scss/_stat.scss
exampleSite/config/_default/config.toml
i18n/en.toml
i18n/zh-hans.toml
i18n/zh-hant.toml
layouts/partials/search/form.html
layouts/partials/search/form/filter-lang.html
layouts/partials/search/modal-footer.html
layouts/partials/search/modal.html
layouts/partials/search/shortcuts.html

Add language filter

---

assets/search/js/engine.ts
assets/search/js/renderer.ts

Show the results score

---

README.md
assets/search/js/renderer.ts
assets/search/scss/_result.scss
config.toml
exampleSite/config/_default/config.toml
layouts/partials/search/functions/params.html

Add the search.expand_results_meta parameter

---

assets/search/js/index.ts
assets/search/scss/_modal.scss
exampleSite/content/bar.zh-hant.md
exampleSite/content/buzz.zh-hans.md
exampleSite/content/buzz.zh-hant.md
exampleSite/content/fizz.zh-hans.md
exampleSite/content/fizz.zh-hant.md
exampleSite/content/foo.zh-hans.md
exampleSite/content/foo.zh-hant.md

Improve UE of modal on large screens

---

assets/search/js/modal.ts
assets/search/scss/_form.scss

Add the input clear button

---

README.md
assets/search/js/drpodown.ts
assets/search/js/modal.ts
assets/search/js/renderer.ts
assets/search/scss/_form.scss
data/search/i18n/en.toml
data/search/i18n/zh-hans.toml
data/search/i18n/zh-hant.toml
layouts/partials/search/assets/js-resource.html

Add sorting support

---

README.md
assets/search/scss/_result.scss
exampleSite/config/_default/config.toml
exampleSite/go.mod
exampleSite/go.sum
exampleSite/layouts/_default/baseof.html
go.mod
go.sum
layouts/partials/search/assets/css-resource.html

Add RTL support

---

assets/search/js/modal.ts

Use current page language to filter results by default

---

assets/search/scss/form/index.scss

Update the search clear button size

---

assets/search/js/drpodown.ts
assets/search/js/form.ts
assets/search/scss/_dropdown.scss

Show the current filter and sorting labels

---

assets/search/js/engine.ts

Avoid engine indexing multiple times

---

assets/search/js/form.ts
assets/search/js/renderer.ts
assets/search/scss/_dropdown.scss
assets/search/scss/_result.scss
assets/search/scss/form/index.scss
data/search/i18n/en.toml
data/search/i18n/zh-hans.toml
data/search/i18n/zh-hant.toml
layouts/partials/search/assets/js-resource.html

Add the expand toggle

---

README.md
assets/search/js/engine.ts
assets/search/js/renderer.ts
assets/search/scss/_result.scss
config.toml
exampleSite/config/_default/config.toml
layouts/partials/search/functions/params.html
layouts/partials/search/index.json.html

Add support for searching by content

---

assets/search/js/engine.ts

Avoid performing a new search when sorting

---

README.md
assets/search/js/form.ts
assets/search/js/modal.ts
assets/search/js/search.ts
exampleSite/config/_default/config.toml
hugo.toml
layouts/partials/search/functions/params.html

feat: lazy loading indices

---

assets/search/js/form.ts

fix: auto focus to search input after initialization

---

assets/search/js/navigator.ts
assets/search/js/renderer.ts
assets/search/scss/_result.scss

fix: remove multiple active results and keep only one

---

data/search/i18n/de.toml
data/search/i18n/en.toml
i18n/de.toml

This PR adds the German translation to the project.

Chore: adding German translation

---

layouts/_default/index.searchindex.json
layouts/partials/search/assets/js-resource.html
layouts/partials/search/functions/search-index-url.html

feat: generate the hash for search indices

---

layouts/partials/search/assets/js-resource.html
layouts/partials/search/functions/pages.html
layouts/partials/search/functions/search-index-hash.html
layouts/partials/search/functions/search-index-url.html
layouts/partials/search/index.json.html

perf: simplify the hashing method

---

data/search/i18n/ms.toml
i18n/ms.toml

chore(i18n): add ms.toml

---

data/search/i18n/ru.toml
i18n/ru.toml

new file:   data/search/i18n/ru.toml	
new file:   i18n/ru.toml

	new file:  ru.toml

---

data/search/i18n/fr.toml
i18n/fr.toml

Hi,
Here is a proposal for the French translations.
Let me know

feat(i18n): add French translations

---

data/search/i18n/pt-br.toml

feat(i18n): fix PT-BR translation file

---

data/search/i18n/de.toml

This PR improves the German translation

chore(i18n): improve German transalation (#89)

---

assets/search/js/form.ts

style: disable input autocomplete

---

assets/search/js/engine.ts
assets/search/js/form.ts

feat: allow searching without keywords

---

assets/search/js/renderer.ts
assets/search/scss/_result.scss
hugo.toml
layouts/partials/search/index.json.html

feat: show page image if present

---

assets/search/js/renderer.ts

fix: stop propagation when selecting history entities

---

assets/search/js/form.ts
assets/search/js/spinner.ts
layouts/partials/search/assets/js-resource.html

style: change spinner icon size to 1.35em

fix: make sure hiding search icon before showing spinner icon

---

assets/search/js/form.ts
assets/search/scss/form/index.scss
layouts/partials/search/assets/js-resource.html

feat: add the reset button

---

exampleSite/layouts/partials/header.html
hugo.toml
layouts/partials/search/assets/css-resource.html
layouts/partials/search/assets/js-resource.html

fix: replace Sites.First with Sites.Default
Bump minimal Hugo version to 0.128.0

fix: replace resources.PostCSS with css.PostCSS

---

assets/search/js/renderer.ts

fix: duplicate matched headings

---

assets/search/js/form.ts

fix: do not disable input after resetting form

---

layouts/partials/search/assets/js-resource.html

fix: check if indices is set

---

assets/search/js/renderer.ts
assets/search/scss/_result.scss
layouts/partials/search/index.json.html

fix: set the height and width attributes for image resources

---

data/search/i18n/es.toml
i18n/es.toml

I'm adding Spanish translation to the search module

Spanish translation for search module
